config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get '/admin', to: 'admin/home#panel', as: :admin_root
  root 'admin/home#panel'


  namespace :admin do 
  	resources :roles
  	resources :sales
  	resources :clients, except: [:index]
  	resources :entries
  	resources :providers
  	resources :warehouses
  	resources :expenses
  	resources :settings, except: [:index, :show, :new, :create, :destroy]
  	
    resources :products do 
    	collection { post :import}
    end
  end

  scope '/admin' do 
		get 'users', to: 'admin/user#landing_users', as: :users_landing
		scope '/users' do 
			get 'list', to: 'admin/user#index_users', as: :users_list
			get 'web-list', to: 'admin/user#web_users', as: :users_web
			get 'new', to: 'admin/user#new', as: :user_new
			get ':id/edit', to: 'admin/user#edit', as: :user_edit

			post '', to: 'admin/user#create', as: :user_create
			put ':id', to: 'admin/user#update', as: :user_update
			patch ':id', to: 'admin/user#update'
			delete ':id', to: 'admin/user#destroy', as: :user_destroy
		end

		get 'clients', to: 'admin/clients#landing_clients', as: :clients_landing
		get 'clients-index', to: 'admin/clients#index', as: :clients_list

		get 'stock-landing', to: 'admin/products#landing', as: :products_landing

		get 'expenses-landing', to: 'admin/pages#landing_expenses', as: :expenses_landing
		get 'sales-landing', to: 'admin/pages#landing_sales', as: :sales_landing

		get 'sales-por-pagar', to: 'admin/sales#por_pagar', as: :sales_por_pagar
		get 'sales-cotizaciones', to: 'admin/sales#cotizaciones', as: :sales_cotizaciones
		get 'sales-parcialmente-pagadas', to: 'admin/sales#parcialmente_pagadas', as: :sales_parcialmente_pagadas
		get 'sales-pagadas', to: 'admin/sales#pagadas', as: :sales_pagadas

		# expenses 
		get 'list-buy', to: 'admin/expenses#index_buy', as: :index_buy

		get 'show-buy/:id', to: 'admin/expenses#show_buy', as: :show_buy
		get 'new-buy', to: 'admin/expenses#new_buy', as: :new_buy
		get 'edit-buy/:id', to: 'admin/expenses#edit_buy', as: :edit_buy
		post 'create-buy', to: 'admin/expenses#create_buy', as: :create_buy
		put 'edit-buy/:id', to: 'admin/expenses#update_buy', as: :update_buy
		patch 'edit-buy/:id', to: 'admin/expenses#update_buy'

		get 'list-nominas', to: 'admin/expenses#index_nomina', as: :index_nomina
		get 'show-nomina/:id', to: 'admin/expenses#show_nomina', as: :show_nomina
		get 'new-nomina', to: 'admin/expenses#new_nomina', as: :new_nomina
		get 'edit-nomina/:id', to: 'admin/expenses#edit_nomina', as: :edit_nomina
		post 'create-nomina', to: 'admin/expenses#create_nomina', as: :create_nomina
		put 'edit-nomina/:id', to: 'admin/expenses#update_nomina', as: :update_nomina
		patch 'edit-nomina/:id', to: 'admin/expenses#update_nomina'


		# product out
		get 'list-exits', to: 'admin/entries#index_out', as: :list_exits
		get 'list-exit/:id', to: 'admin/entries#show_out', as: :show_exit
		get 'product-out', to: 'admin/entries#product_out', as: :new_out
		get 'edit-out/:id', to: 'admin/entries#edit_out', as: :edit_out
		post '', to: 'admin/entries#create_out', as: :create_out
		put 'edit-out/:id', to: 'admin/entries#update_out', as: :update_out
		patch 'edit-out/:id', to: 'admin/entries#update_out'

		get 'reports', to: 'admin/pages#reports', as: :reports

	end
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/client.rb
class Client < ApplicationRecord
	Limite = [0, 2000, 5000, 7000, 10000, 15000, 20000, 25000]

	validates :razon, :name, :rfc, :state, :city, :cp, :col, :address, :ext_number, :phone_1, :email, presence: true
	validates :razon, uniqueness: true
	# has_many :charges
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
  # roles who aply here :super  
  before_action :check_admin
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  def landing_clients
    
  end

  # GET /admin/clients
  # GET /admin/clients.json
  def index
    @q = Client.ransack(params[:q])
    @clients = @q.result(distinct: true).order(name: :desc)
  end

  # GET /admin/clients/1
  # GET /admin/clients/1.json
  def show
  end

  # GET /admin/clients/new
  def new
    @client = Client.new
    @limit = Client::Limite
  end

  # GET /admin/clients/1/edit
  def edit
    @limit = Client::Limite

  end

  # POST /admin/clients
  # POST /admin/clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_list_path, notice: 'Client was successfully created.' }
        # format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        # format.json { render json: @admin_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/clients/1
  # PATCH/PUT /admin/clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to clients_list_path, notice: 'Client was successfully updated.' }
        # format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        # format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/clients/1
  # DELETE /admin/clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_list_path, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_admin
      unless current_user.has_roles?([:super, :admin, :ventas, :gerente_ventas])
        redirect_to admin_root_path, notice: "Error 9001 no tienes permiso"
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:razon, :name, :rfc, :address, :col, :cp, :state, :city, :localidad, :phone_1, :phone_2, :ext_number, :int_number, :email, :credit_limit, :tipo_venta)

    end
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/views/admin/clients/_form.html.erb
<%= simple_form_for(client, url: url) do |f| %>
  <%= f.error_notification %>

  <%= f.input :razon, label: "Razón social" %>
  <%= f.input :name, label: "Alias" %>
  <%= f.input :rfc, label: "RFC" %>
  <%= f.input :state, label: "Estado" %>
  <%= f.input :city, label: "Ciudad" %>
  <%= f.input :localidad, label: "Localidad" %>
  <%= f.input :cp, label: "Código postal" %>
  <%= f.input :col, label: "Colonia" %>
  <%= f.input :address, label: "Dirección" %>
  <%= f.input :ext_number, label: "Número exterior" %>
  <%= f.input :int_number, label: "Número interior" %>
  <%= f.input :phone_1, label: "Teléfono" %>
  <%= f.input :phone_2, label: "Teléfono 2" %>
  <%= f.input :email, label: "Email" %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success btn-block" %>
  </div>
<% end %>

app/views/admin/clients/edit.html.erb
<h1>Editing Admin Client</h1>

<%= render 'form', client: @client, url: admin_client_path(@client) %>

app/views/admin/clients/index.html.erb
<br>
<p>Buscador</p>
<%= search_form_for @q, url: clients_list_path, html: {class: "form-inline"} do |f| %>
    <%= f.search_field :razon_cont, placeholder: "razón social", class: "form-control" %>
    <%= f.search_field :state_or_city_cont, placeholder: "estado, ciudad", class: "form-control" %>
    <%= f.search_field :email_cont, placeholder: "email", class: "form-control" %>
    <%= f.search_field :phone_1_or_phone_2_cont, placeholder: "teléfono", class: "form-control" %>
    <%= f.submit 'Buscar', class: "btn btn-primary" %>
    <%= link_to clients_list_path, class: "btn btn-success" do  %>
       <span class="glyphicon glyphicon-erase" aria-hidden="true"></span>
       Reset
    <% end %>
    <br><br>
    <% if current_user.has_roles? [:super, :admin] %>
      <%= link_to admin_products_path(format: 'csv'), class: "btn btn-success" do  %>
         <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
         Descargar CSV
      <% end %>

      <%= link_to admin_products_path(format: "pdf"), class: "btn btn-success" do %>
        <span class="glyphicon glyphicon-download" aria-hidden="true"></span> 
        Descargar PDF
      <% end %>
    <% end %>
    
<% end %>

<h1>Clientes</h1>
<hr>
<table class="table">
  <thead>
    <tr>
      <th>Razón</th>
      <th>Estado</th>
      <th>Ciudad</th>
      <th>Mail</th>
      <th>Teléfono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.razon %></td>
        <td><%= client.state %></td>
        <td><%= client.city %></td>
        <td><%= client.email %></td>
        <td><%= client.phone_1 %></td>

        <td><%= link_to 'ver más', admin_client_path(client) %></td>
        <% if current_user.has_roles? [:super, :admin, :gerente_ventas, :ventas] %>
          <td><%= link_to 'editar', edit_admin_client_path(client) %></td>
        <% end %>
        <% if current_user.has_roles? [:super, :admin] %>
          <td><%= link_to 'Destroy', admin_client_path(client), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/clients/landing_clients.html.erb
<% @title = "Manejo de clientes" %>

<div class="">
	
	<% if current_user.has_roles? [:super, :admin, :ventas, :gerente_ventas] %>
		<a href="<%= new_admin_client_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'plus.svg' %>
					<p>Nuevo cliente</p>
				</div>
			</div>
		</a>
		<a href="<%= new_admin_provider_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'plus.svg' %>
					<p>Nuevo Proveedor</p>
				</div>
			</div>
		</a>
		<a href="<%= clients_list_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'list.svg' %>
					<p>Listado de clientes</p>
				</div>
			</div>
		</a>
		<a href="<%= admin_providers_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'list.svg' %>
					<p>Listado de proveedores</p>
				</div>
			</div>
		</a>
		
	<% end %>

	
</div>

app/views/admin/clients/new.html.erb
<h1>Nuevo cliente</h1>

<%= render 'form', client: @client, url: admin_clients_path(@client) %>

app/views/admin/clients/show.html.erb
<br>

<hr>
<p>
	<b>Razon social: </b>
	<%= @client.razon %>
</p>
<p>
	<b>Nombre: </b>
	<%= @client.name %>
</p>
<p>
	<b>RFC: </b>
	<%= @client.rfc %>
</p>
<p>
	<b>Estado: </b>
	<%= @client.state %>
</p>
<p>
	<b>Ciudad: </b>
	<%= @client.city %>
</p>
<p>
	<b>Localidad: </b>
	<%= @client.localidad %>
</p>
<p>
	<b>CP: </b>
	<%= @client.cp %>
</p>
<p>
	<b>Colonia: </b>
	<%= @client.col %>
</p>
<p>
	<b>Direccion: </b>
	<%= @client.address %>
</p>
<p>
	<b>Numero exterior: </b>
	<%= @client.ext_number %>
</p>
<p>
	<b>Numero interior: </b>
	<%= @client.int_number %>
</p>
<p>
	<b>Telefono 1: </b>
	<%= @client.phone_1 %>
</p>
<p>
	<b>Telefono 2: </b>
	<%= @client.phone_2 %>
</p>
<p>
	<b>Email: </b>
	<%= @client.email %>
</p>
<p>
	<b>Limite de credito: </b>
	<%= @client.credit_limit %>
</p>