config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  get '/admin', to: 'admin/home#panel', as: :admin_root
  root 'admin/home#panel'


  namespace :admin do 
  	resources :roles
  	resources :sales
  	resources :clients, except: [:index]
  	resources :entries
  	resources :providers
  	resources :warehouses
  	resources :expenses
  	resources :settings, except: [:index, :show, :new, :create, :destroy]
  	
    resources :products do 
    	collection { post :import}
    end
  end

  scope '/admin' do 
		get 'users', to: 'admin/user#landing_users', as: :users_landing
		scope '/users' do 
			get 'list', to: 'admin/user#index_users', as: :users_list
			get 'web-list', to: 'admin/user#web_users', as: :users_web
			get 'new', to: 'admin/user#new', as: :user_new
			get ':id/edit', to: 'admin/user#edit', as: :user_edit

			post '', to: 'admin/user#create', as: :user_create
			put ':id', to: 'admin/user#update', as: :user_update
			patch ':id', to: 'admin/user#update'
			delete ':id', to: 'admin/user#destroy', as: :user_destroy
		end

		get 'clients', to: 'admin/clients#landing_clients', as: :clients_landing
		get 'clients-index', to: 'admin/clients#index', as: :clients_list

		get 'stock-landing', to: 'admin/products#landing', as: :products_landing

		get 'expenses-landing', to: 'admin/pages#landing_expenses', as: :expenses_landing
		get 'sales-landing', to: 'admin/pages#landing_sales', as: :sales_landing

		get 'sales-por-pagar', to: 'admin/sales#por_pagar', as: :sales_por_pagar
		get 'sales-cotizaciones', to: 'admin/sales#cotizaciones', as: :sales_cotizaciones
		get 'sales-parcialmente-pagadas', to: 'admin/sales#parcialmente_pagadas', as: :sales_parcialmente_pagadas
		get 'sales-pagadas', to: 'admin/sales#pagadas', as: :sales_pagadas

		# expenses 
		get 'list-buy', to: 'admin/expenses#index_buy', as: :index_buy

		get 'show-buy/:id', to: 'admin/expenses#show_buy', as: :show_buy
		get 'new-buy', to: 'admin/expenses#new_buy', as: :new_buy
		get 'edit-buy/:id', to: 'admin/expenses#edit_buy', as: :edit_buy
		post 'create-buy', to: 'admin/expenses#create_buy', as: :create_buy
		put 'edit-buy/:id', to: 'admin/expenses#update_buy', as: :update_buy
		patch 'edit-buy/:id', to: 'admin/expenses#update_buy'

		get 'list-nominas', to: 'admin/expenses#index_nomina', as: :index_nomina
		get 'show-nomina/:id', to: 'admin/expenses#show_nomina', as: :show_nomina
		get 'new-nomina', to: 'admin/expenses#new_nomina', as: :new_nomina
		get 'edit-nomina/:id', to: 'admin/expenses#edit_nomina', as: :edit_nomina
		post 'create-nomina', to: 'admin/expenses#create_nomina', as: :create_nomina
		put 'edit-nomina/:id', to: 'admin/expenses#update_nomina', as: :update_nomina
		patch 'edit-nomina/:id', to: 'admin/expenses#update_nomina'


		# product out
		get 'list-exits', to: 'admin/entries#index_out', as: :list_exits
		get 'list-exit/:id', to: 'admin/entries#show_out', as: :show_exit
		get 'product-out', to: 'admin/entries#product_out', as: :new_out
		get 'edit-out/:id', to: 'admin/entries#edit_out', as: :edit_out
		post '', to: 'admin/entries#create_out', as: :create_out
		put 'edit-out/:id', to: 'admin/entries#update_out', as: :update_out
		patch 'edit-out/:id', to: 'admin/entries#update_out'

		get 'reports', to: 'admin/pages#reports', as: :reports

	end
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/product.rb
class Product < ApplicationRecord
  # Tipos = %i[llanta rin accesorio]
  Tipos = [['Materia prima', :materia_prima], ['Herramienta', :herramienta], ['Maquinaria', :maquinaria],['Producto terminado', :producto]]
  Unidades = [['Pieza', :pieza], ['Reja 12pzs', :reja_12], ['Reja 24pzs', :reja_24],['Caja', :caja], ['Litro', :l], ['Kg', :kg], ['Metro', :m],['Gramo', :gr], ['Mililitro', :ml]]

  has_many :entries_products
  has_many :entries, through: :entries_products



  has_many :line_expenses
  # has_many :expenses, through: :line_expenses

  has_many :line_buys
  # has_many :expenses, through: :line_buys

  belongs_to :provider

  validates :model, :public_price, :product_type, :sku, presence: true
  # validates :model, uniqueness: true

  def name_a
    "#{id} - #{model} (#{unidad})"
  end
  def name_d
    "#{id} - #{model} (#{unidad}) - ($ #{public_price})"
  end 

  def self.import(file)
    # CSV.foreach(file.path, headers: true) do |row|
    #     begin
    #       object = self.find(row[:id])
    #       if object.present?
    #         object.update!(row.to_hash)
    #       end
    #     rescue  
    #       self.create!(row.to_hash)
    #     end
    # end

    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by(id: row["id"]) || new
      product.attributes = row.to_hash
      # product.brand = product.brand.upcase
      product.model = product.model.upcase
      product.sku = "#{product.brand[0..2]}#{product.model[0..3]}#{product.ancho}-#{product.alto}-#{product.rin}"
      product.save!
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # role who apply here :super, :admin, :inventario, :gerente_inventario
  before_action :check_admin
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  def landing
  end

  def import
    Product.import(params[:file])
    redirect_to admin_products_path, notice: "Productos importados!"
  end

  # GET /admin/products
  # GET /admin/products.json
  # GET /admin/products.csv
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
    respond_to do |f|
      f.html
      f.csv 
      f.pdf do
        pdf = ProductosPdf.new(@products)
        send_data(pdf.render, filename: "products_#{Time.now}.pdf", type: "application/pdf", disposition: "inline")
      end
    end
  end


  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @product = Product.new
    @product_types = Product::Tipos
    @unidades = Product::Unidades
  end

  # GET /admin/products/1/edit
  def edit
    @product_types = Product::Tipos
    @unidades = Product::Unidades

  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    # @product_types = Product::Tipos

    @product = Product.new(product_params)
    @product.brand = @product.brand.upcase
    @product.model = @product.model.upcase
    @product.sku = @product.sku.upcase
    
    # @product.sku = "#{@product.brand[0..2]}#{@product.model[0..3]}#{@product.ancho}-#{@product.alto}-#{@product.rin}"
    
    # precio medio mayoreo
    @product.price_1 = (@product.public_price * 0.95)

    # precio mayoreo
    @product.price_2 = (@product.public_price * 0.93)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), id: @product.id, notice: 'Producto fue creado' }
        # format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        # format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    @product.assign_attributes(product_params)
    @product.brand = @product.brand.upcase
    @product.model = @product.model.upcase
    @product.sku = @product.sku.upcase
    # @product.sku = "#{@product.brand[0..2]}#{@product.model[0..3]}#{@product.ancho}-#{@product.alto}-#{@product.rin}"
    
    # @product.save
    # precio medio mayoreo
    @product.price_1 = (@product.public_price * 0.95)
    # precio mayoreo
    @product.price_2 = (@product.public_price * 0.93)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: 'Producto fue actualizado' }
        # format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        # format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Producto fue destruido' }
      # format.json { head :no_content }
    end
  end

  private
    def check_admin
      unless current_user.has_roles?([:super, :admin, :gerente_inventario, :inventario])
        redirect_to admin_root_path, notice: "Error 9001 no tienes permiso"
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:capacity, :unidad, :cost, :product_type, :sku, :brand, :model, :ancho, :alto, :rin, :treadwear, :desc, :ind_carga, :ind_velocidad, :public_price, :price_2, :price_1)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for(product, url: url) do |f| %>
  <%= f.error_notification %>

  	<%= f.input :product_type, collection: @product_types, prompt: "Selecciona tipo de producto", label: false %>
    <%= f.input :model, label: "Nombre" %>
    <%= f.input :sku, label: "SKU" %>
    <%= f.input :unidad, collection: @unidades, label: "Unidad", required: true, input_html: {class: "input perfil"} %>
  	<%= f.input :capacity, label: "Capacidad" %>


    <%= f.input :public_price, label: "Precio" %>
    <%= f.input :cost, label: "Costo"%>
  	<%= f.input :desc, label: "Descripcion "%>

  <div class="form-actions">
    <%= f.button :submit, 'Guardar', class: "btn btn-success btn-block", id: 'btn-margin-bottom' %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<br>
<h1>Editar producto</h1>

<%= render 'form', product: @product, url: admin_product_path(@product) %>

app/views/admin/products/index.csv.erb
ID,Nombre,Unidad,Capacidad,Cantidad,Precio,Precio Medio-mayoreo (5%),Precio Mayoreo (7%)
<% @products.each do |p| %>
  <%= p.id %>,<%= p.model %>,<%= p.unidad %>,<%= p.capacity %>,<%= p.quantity %>,<%= p.public_price %>,<%= p.price_1 %>,<%= p.price_2 %>
<% end %>

app/views/admin/products/index.html.erb
<br>
<p>Buscador</p>
<%= search_form_for @q, url: admin_products_path, html: {class: "form-inline"} do |f| %>

    <%= f.search_field :sku_cont, placeholder: "ID", class: "form-control col-xm-1" %>
    <%= f.search_field :model_cont, placeholder: "nombre", class: "form-control" %>

    <%= f.submit 'Buscar', class: "btn btn-primary" %>
    <%= link_to admin_products_path, class: "btn btn-success" do  %>
       <span class="glyphicon glyphicon-erase" aria-hidden="true"></span>
       Reset
    <% end %>
    <br><br>
    <%= link_to admin_products_path(format: 'csv'), class: "btn btn-success" do  %>
       <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
       Descargar CSV
    <% end %>

    <%= link_to admin_products_path(format: "pdf"), class: "btn btn-success" do %>
      <span class="glyphicon glyphicon-download" aria-hidden="true"></span> 
      Descargar PDF
    <% end %>
    <% if current_user.has_roles? [:super, :admin] %>
      <a href="#" class="btn btn-warning" title="Masive import" data-toggle="modal" data-target="#import">
        <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Importar CSV 
      </a>
    <% end %>
    
<% end %>
<h1>Productos</h1>
<hr>

<table class="table">
  <thead>
    <tr>
      <th>SKU</th>
      <th><%= sort_link @q, :model, 'Nombre' %></th>
      <th><%= sort_link @q, :capacity, 'Capacidad' %></th>
      <th><%= sort_link @q, :unidad, 'Unidad' %></th>


      <th><%= sort_link @q, :quantity, 'Cantidad' %></th>
      <th><%= sort_link @q, :public_price, 'Precio' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.sku %></td>
        <td><%= product.model %></td>
        <td><%= product.capacity %></td>
        <td><%= product.unidad.humanize %></td>


        <td><%= product.quantity %></td>
        <td>
          <select class="form-control">
            <option>Publico: <%= number_to_currency(product.public_price) %></option>
            <% if current_user.has_any_role? %>
              <option>Medio-mayoreo: <%= number_to_currency(product.price_1) %></option>
              <option>Mayoreo: <%= number_to_currency(product.price_2) %></option>

              <% if product.cost and current_user.has_roles? [:super, :admin]%>
                <option>Costo: <%= number_to_currency(product.cost) %></option>
              <% end %>
            <% end %>
          </select>
        </td>

        <td><%= link_to 'Ver', admin_product_path(product) %></td>

        <% if current_user.has_roles? [:super, :admin, :inventario, :gerente_inventario] %>
          <td><%= link_to 'Editar', edit_admin_product_path(product) %></td>
          <td><%= link_to 'Destruir', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.has_roles? [:super, :admin] %>
  <div class="modal fade" id="import" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        
        <div class="modal-body text-center">
          <%= form_tag(import_admin_products_path, multipart: true) do  %>
            <%= file_field_tag :file %>
            <br>
            <%= submit_tag "Importar", class: "btn btn-success btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/products/landing.html.erb
<% @title = "Inventario" %>

<div class="">
	
	<% if current_user.has_roles? [:super, :admin, :gerente_ventas, :gerente_compras, :gerente_inventario, :inventario] %>
		<a href="<%= new_out_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'plus.svg' %>
					<p>Salida de mercancia</p>
				</div>
			</div>
		</a>
		<a href="<%= new_admin_entry_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'plus.svg' %>
					<p>Entrada de mercancia</p>
				</div>
			</div>
		</a>
		<a href="<%= new_admin_product_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'plus.svg' %>
					<p>Nuevo producto</p>
				</div>
			</div>
		</a>
		<a href="<%= admin_entries_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'list.svg' %>
					<p>Ver entradas de mercancia</p>
				</div>
			</div>
		</a>
		<a href="<%= list_exits_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'list.svg' %>
					<p>Ver salidas de mercancia</p>
				</div>
			</div>
		</a>
		<a href="<%= admin_products_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'list.svg' %>
					<p>Ver inventario</p>
				</div>
			</div>
		</a>
		<a href="<%= admin_warehouses_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'list.svg' %>
					<p>Bodegas</p>
				</div>
			</div>
		</a>
	<% end %>
	<% if current_user.has_roles? [:super, :admin, :gerente_inventario, :gerente_compras, :gerente_ventas] %>
		<a href="<%= new_admin_warehouse_path %>">
			<div class="col-sm-6 col-md-3 box">
				<div class="box-border">
					<%= image_tag 'plus.svg' %>
					<p>Nueva bodega</p>
				</div>
			</div>
		</a>
	<% end %>

	
</div>

app/views/admin/products/new.html.erb
<br>
<h1>Nuevo producto</h1>

<%= render 'form', product: @product, url: admin_products_path(@product) %>

app/views/admin/products/show.html.erb
<br>

<hr>
<p>
	<b>Tipo de producto: </b>
	<%= @product.product_type.humanize %>
</p>
<p>
	<b>Clave: </b>
	<%= @product.sku %>
</p>

<p>
	<b>Nombre: </b>
	<%= @product.model %>
</p>
<% if @product.capacity %>
<p>
	<b>Capacidad: </b>
	<%= @product.capacity %>
</p>
<% end %>
<p>
	<b>Unidad: </b>
	<%= @product.unidad.humanize %>
</p>

<p>
	<b>Precio de costo: </b>
	$ <%= @product.cost %>
</p>
<p>
	<b>Precio al público: </b>
	$ <%= @product.public_price %>
</p>
<p>
	<b>Precio Medio-mayoreo (5%): </b>
	<%= number_to_currency @product.price_1 %>
</p>
<p>
	<b>Precio Mayoreo (7%): </b>
	<%= number_to_currency @product.price_2 %>
</p>